
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 06 02:34:17 CEST 2017
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVEQ = 49;
  public static final int PLUSPLUS = 35;
  public static final int GTEQ = 41;
  public static final int MULT = 32;
  public static final int CONST = 6;
  public static final int LTEQ = 42;
  public static final int CHAR_LITERAL = 19;
  public static final int MODEQ = 50;
  public static final int LPAREN = 24;
  public static final int CONTINUE = 15;
  public static final int FOR = 13;
  public static final int MINUS = 31;
  public static final int STATIC = 16;
  public static final int RPAREN = 25;
  public static final int OROR = 44;
  public static final int SEMICOLON = 21;
  public static final int LT = 40;
  public static final int COMMA = 22;
  public static final int CLASS = 4;
  public static final int ANDAND = 43;
  public static final int DIV = 33;
  public static final int PLUSEQ = 46;
  public static final int MINUSEQ = 47;
  public static final int PLUS = 30;
  public static final int IF = 7;
  public static final int DOT = 23;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 36;
  public static final int RETURN = 11;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int EQEQ = 37;
  public static final int MULTEQ = 48;
  public static final int MOD = 34;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int EQ = 45;
  public static final int LBRACK = 26;
  public static final int LBRACE = 28;
  public static final int ELSE = 5;
  public static final int READ = 10;
  public static final int RBRACK = 27;
  public static final int RBRACE = 29;
  public static final int EXTENDS = 14;
  public static final int GT = 39;
  public static final int PRINT = 9;
  public static final int BOOL_LITERAL = 20;
  public static final int NOTEQ = 38;
  public static final int INTEGER_LITERAL = 18;
  public static final int IDENTIFIER = 17;
}

